# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHistoryAnalysis = channel.unary_stream(
                '/analysis.StockAnalyzer/GetHistoryAnalysis',
                request_serializer=analysis__pb2.StockRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResult.FromString,
                _registered_method=True)


class StockAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHistoryAnalysis(self, request, context):
        """服务端流式：一个请求，返回一个结果流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHistoryAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHistoryAnalysis,
                    request_deserializer=analysis__pb2.StockRequest.FromString,
                    response_serializer=analysis__pb2.AnalysisResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.StockAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.StockAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHistoryAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/analysis.StockAnalyzer/GetHistoryAnalysis',
            analysis__pb2.StockRequest.SerializeToString,
            analysis__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
