# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\"\n\x0cStockRequest\x12\x12\n\nstock_code\x18\x01 \x01(\t\"@\n\x0e\x41nalysisResult\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x11\n\tsentiment\x18\x03 \x01(\t2Y\n\rStockAnalyzer\x12H\n\x12GetHistoryAnalysis\x12\x16.analysis.StockRequest\x1a\x18.analysis.AnalysisResult0\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_STOCKREQUEST']._serialized_start=28
  _globals['_STOCKREQUEST']._serialized_end=62
  _globals['_ANALYSISRESULT']._serialized_start=64
  _globals['_ANALYSISRESULT']._serialized_end=128
  _globals['_STOCKANALYZER']._serialized_start=130
  _globals['_STOCKANALYZER']._serialized_end=219
# @@protoc_insertion_point(module_scope)
