// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: analysis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockAnalyzer_GetHistoryAnalysis_FullMethodName = "/analysis.StockAnalyzer/GetHistoryAnalysis"
)

// StockAnalyzerClient is the client API for StockAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockAnalyzerClient interface {
	// 服务端流式：一个请求，返回一个结果流
	GetHistoryAnalysis(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisResult], error)
}

type stockAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewStockAnalyzerClient(cc grpc.ClientConnInterface) StockAnalyzerClient {
	return &stockAnalyzerClient{cc}
}

func (c *stockAnalyzerClient) GetHistoryAnalysis(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockAnalyzer_ServiceDesc.Streams[0], StockAnalyzer_GetHistoryAnalysis_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StockRequest, AnalysisResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockAnalyzer_GetHistoryAnalysisClient = grpc.ServerStreamingClient[AnalysisResult]

// StockAnalyzerServer is the server API for StockAnalyzer service.
// All implementations must embed UnimplementedStockAnalyzerServer
// for forward compatibility.
type StockAnalyzerServer interface {
	// 服务端流式：一个请求，返回一个结果流
	GetHistoryAnalysis(*StockRequest, grpc.ServerStreamingServer[AnalysisResult]) error
	mustEmbedUnimplementedStockAnalyzerServer()
}

// UnimplementedStockAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockAnalyzerServer struct{}

func (UnimplementedStockAnalyzerServer) GetHistoryAnalysis(*StockRequest, grpc.ServerStreamingServer[AnalysisResult]) error {
	return status.Error(codes.Unimplemented, "method GetHistoryAnalysis not implemented")
}
func (UnimplementedStockAnalyzerServer) mustEmbedUnimplementedStockAnalyzerServer() {}
func (UnimplementedStockAnalyzerServer) testEmbeddedByValue()                       {}

// UnsafeStockAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockAnalyzerServer will
// result in compilation errors.
type UnsafeStockAnalyzerServer interface {
	mustEmbedUnimplementedStockAnalyzerServer()
}

func RegisterStockAnalyzerServer(s grpc.ServiceRegistrar, srv StockAnalyzerServer) {
	// If the following call panics, it indicates UnimplementedStockAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockAnalyzer_ServiceDesc, srv)
}

func _StockAnalyzer_GetHistoryAnalysis_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockAnalyzerServer).GetHistoryAnalysis(m, &grpc.GenericServerStream[StockRequest, AnalysisResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockAnalyzer_GetHistoryAnalysisServer = grpc.ServerStreamingServer[AnalysisResult]

// StockAnalyzer_ServiceDesc is the grpc.ServiceDesc for StockAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.StockAnalyzer",
	HandlerType: (*StockAnalyzerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHistoryAnalysis",
			Handler:       _StockAnalyzer_GetHistoryAnalysis_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "analysis.proto",
}
